pub mod auth;
pub mod blocking;
pub mod database;
pub mod dns;
pub mod encrypted_dns;
pub mod errors;
pub mod health;
pub mod local_records;
pub mod logging;
pub mod rate_limit;
pub mod root;
pub mod server;
pub mod upstream;
pub mod web_tls;

pub use auth::{AdminConfig, AuthConfig};
pub use blocking::BlockingConfig;
pub use database::DatabaseConfig;
pub use dns::DnsConfig;
pub use encrypted_dns::EncryptedDnsConfig;
pub use errors::ConfigError;
pub use health::HealthCheckConfig;
pub use local_records::LocalDnsRecord;
pub use logging::LoggingConfig;
pub use rate_limit::RateLimitConfig;
pub use root::{CliOverrides, Config};
pub use server::ServerConfig;
pub use upstream::{UpstreamPool, UpstreamStrategy};
pub use web_tls::WebTlsConfig;
