pub mod blocking;
pub mod database;
pub mod dns;
pub mod errors;
pub mod health;
pub mod local_records;
pub mod logging;
pub mod root;
pub mod server;
pub mod upstream;

pub use blocking::BlockingConfig;
pub use database::DatabaseConfig;
pub use dns::{ConditionalForward, DnsConfig};
pub use errors::ConfigError;
pub use health::HealthCheckConfig;
pub use local_records::LocalDnsRecord;
pub use logging::LoggingConfig;
pub use root::{CliOverrides, Config};
pub use server::ServerConfig;
pub use upstream::{UpstreamPool, UpstreamStrategy};
