pub mod blocklist;
pub mod cache;
pub mod client_groups;
pub mod client_subnets;
pub mod clients;
pub mod config;
pub mod groups;
pub mod health;
pub mod hostname;
pub mod local_records;
pub mod manual_clients;
pub mod queries;
pub mod rate;
pub mod stats;
pub mod timeline;

pub use blocklist::get_blocklist;
pub use cache::{get_cache_metrics, get_cache_stats};
pub use client_groups::assign_client_to_group;
pub use clients::{get_client_stats, get_clients};
pub use config::{get_config, get_settings, reload_config, update_config, update_settings};
pub use health::health_check;
pub use hostname::get_hostname;
pub use manual_clients::{create_manual_client, delete_manual_client};
pub use queries::get_queries;
pub use rate::get_query_rate;
pub use stats::get_stats;
pub use timeline::get_timeline;
pub mod upstream;
