server:
    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    access-control: 0.0.0.0/0 allow
    cache-max-ttl: 86400
    cache-min-ttl: 0
    msg-cache-size: 64m
    rrset-cache-size: 128m
    num-threads: 2
    so-reuseport: yes
    outgoing-range: 4096
    num-queries-per-thread: 2048
    verbosity: 0
    do-not-query-localhost: no

forward-zone:
    name: "."
    forward-addr: 8.8.8.8@53
    forward-addr: 1.1.1.1@53
